In [21]:
import numpy as np
import pandas as pd
import tqdm
import math

In [4]:
df = pd.read_csv("./de/full_data/dataset.csv")

In [42]:
df.keys()

Index(['Unnamed: 0', 'locat', 'price', 'paycode', 'make', 'oost', 'mpt', 'mvi',
       'split_pay_amt', 'split_pay_code', 'depositnum', 'workdaynum',
       'manual_entry', 'earlybird', 'correctedpayment', 'rateid', 'lane',
       'facility', 'extralng1', 'extracur1', 'extrastr1', 'freespot',
       'converted', 'vehiclemodel', 'nightmonthly', 'originalprice',
       'mpsreplacement ', 'ccdaccount', 'ccdexpdate', 'ccdmanualentry',
       'previouspayments', 'prepayamount', 'prepaycode', 'shiftid',
       'thepricewascorrected', 'checkinws', 'checkoutws', 'oldpaycode',
       'correctiontime', 'splitpayment', 'hasrefund', 'refundamnt',
       'receiptsprinted', 'rushmode', 'ratedescription', 'eventratemode',
       'paymentdescription', 'facilitysection', 'facilitylocation', 'exitused',
       'prepayversion', 'uptohours', 'pdamount', 'oversizeamount',
       'ppccreader', 'coupontype', 'couponvalue', 'stickernumber',
       'checkincard', 'checkoutcard', 'prepayccdaccount', 'changedue'

In [45]:
df.values[0, :]

array([0, 705, 0.0, 9, 'BMW', 0, nan, nan, 0.0, nan, 1, 155, 0, 0, 0, 0,
       0, 0, 0, 0.0, nan, 0, 0, 4, 0, 0.0, nan, '    ', '    ', 0, 0.0,
       0.0, nan, 4254, 0, 12, 12, nan, nan, 0, 0, 0.0, 0, 0, nan, 0,
       'Monthly', '  ', '    ', ' ', nan, '     ', 0.0, 0.0, 0, nan, nan,
       '20', 'CheckinCheckout', 'POS012 ', ' ', 0.0, 18.375, 0.0, 0],
      dtype=object)

In [51]:
string_index=[]
for n, i in enumerate(df.values[0, :]):
    if isinstance(i, float) or isinstance(i, int):
        pass
    else:
        string_index.append(n)

In [52]:
string_index

[4, 27, 28, 46, 47, 48, 49, 51, 57, 58, 59, 60]

In [53]:
df.values[:, 4]

array(['BMW', 'Jeep', 'Benz', ..., 'Toyota', 'Benz', 'Jeep'], dtype=object)

In [78]:
li = []
for val in df.values[:, 4]:
    if val not in li:
        if isinstance(val, str):
            li.append(val)
    else:
        pass

In [89]:
onehot_index_4 = sorted(li)

In [90]:
print(onehot_index_4)

['Acura', 'Alfa Romeo', 'Aston Mart', 'Audi', 'BMW', 'Bentley', 'Benz', 'Bicycle', 'Buick', 'Caddy', 'Chevy', 'Chrys', 'Cycle', 'Dodge', 'Ferrari', 'Fiat', 'Ford', 'Geo', 'Gmc', 'Honda', 'Hummer', 'Hyundai', 'Infini', 'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Lamborghin', 'Lexus', 'Lincoln', 'Maserati', 'Maybach', 'Mazda', 'Merc', 'Mini Coope', 'Mitsu', 'Motorcycle', 'Nissan', 'Olds', 'Other', 'Oversize', 'Plym', 'Pontiac', 'Porsche', 'Rolls', 'Rover', 'SUV', 'Saab', 'Saturn', 'Scion', 'Smart', 'Subaru', 'Superovers', 'Suzuki', 'Tesla', 'Toyota', 'Truck', 'Volks', 'Volvo']


In [93]:
x = np.zeros(len(onehot_index_4))
x[onehot_index_4.index('Acura')] = 1

In [94]:
x

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [101]:
for n, i in enumerate(array_df[:, 4]):
    if isinstance(i, str):
        temp = np.zeros(len(onehot_index_4))
        temp[onehot_index_4.index(i)] = 1
        array_df[n, 4] = temp
    else:
        temp = np.zeros(len(onehot_index_4))
        array_df[n, 4] = temp 

In [106]:
array_df[:, 4][1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [107]:
array_df.shape

(99994, 65)

In [110]:
def change_one_hot():
    df = pd.read_csv("./de/full_data/dataset.csv")
    array_df = np.array(df)
    key_dict = {}
    string_index=[]
    for n, i in enumerate(df.values[0, :]):
        if isinstance(i, float) or isinstance(i, int):
            pass
        else:
            string_index.append(n)
    for index in tqdm.tqdm(string_index):
        li = []
        for val in df.values[:, index]:
            if val not in li:
                if isinstance(val, str):
                    li.append(val)
            else:
                pass
        key_dict["key_"+df.keys()[index]] = sorted(li)
        for n, i in enumerate(array_df[:, index]):
            if isinstance(i, str):
                temp = np.zeros(len(key_dict["key_"+df.keys()[index]]))
                temp[key_dict["key_"+df.keys()[index]].index(i)] = 1
                array_df[n, index] = temp
            else:
                temp = np.zeros(len(key_dict["key_"+df.keys()[index]]))
                array_df[n, index] = temp 
    return array_df, key_dict

In [111]:
array_df, key_dict = change_one_hot()

100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:18<00:00,  1.60s/it]


In [117]:
key_dict

{'key_make': ['Acura',
  'Alfa Romeo',
  'Aston Mart',
  'Audi',
  'BMW',
  'Bentley',
  'Benz',
  'Bicycle',
  'Buick',
  'Caddy',
  'Chevy',
  'Chrys',
  'Cycle',
  'Dodge',
  'Ferrari',
  'Fiat',
  'Ford',
  'Geo',
  'Gmc',
  'Honda',
  'Hummer',
  'Hyundai',
  'Infini',
  'Isuzu',
  'Jaguar',
  'Jeep',
  'Kia',
  'Lamborghin',
  'Lexus',
  'Lincoln',
  'Maserati',
  'Maybach',
  'Mazda',
  'Merc',
  'Mini Coope',
  'Mitsu',
  'Motorcycle',
  'Nissan',
  'Olds',
  'Other',
  'Oversize',
  'Plym',
  'Pontiac',
  'Porsche',
  'Rolls',
  'Rover',
  'SUV',
  'Saab',
  'Saturn',
  'Scion',
  'Smart',
  'Subaru',
  'Superovers',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Truck',
  'Volks',
  'Volvo'],
 'key_ccdaccount': [' ',
  '    ',
  '0000',
  '0001',
  '0002',
  '0003',
  '0004',
  '0005',
  '0006',
  '0007',
  '0008',
  '0009',
  '0010',
  '0011',
  '0013',
  '0014',
  '0015',
  '0016',
  '0017',
  '0018',
  '0019',
  '0020',
  '0021',
  '0022',
  '0023',
  '0024',
  '0025',
  '0026',
  